-- COUNT할 때 같은 년도, 같은 월에 상품을 구매한 회원이 있는 걸 간과했다.
-- COUNT 함수 안에 DISTINCT로 같은 USER_ID는 걸러서 세야 정답이다.
-- 코드를 입력하세요
SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT(U.USER_ID)) AS USERS
FROM
    USER_INFO U
JOIN
    ONLINE_SALE O ON U.USER_ID = O.USER_ID
WHERE
    GENDER IS NOT NULL
GROUP BY
    YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY
    YEAR, MONTH, GENDER;