"""
1. ECOLI_DATA를 자식(C), 부모(P) 테이블로 각각 불러오기.
2. C의 PARENT_ID와 P의 ID가 같을 때 JOIN
3. C의 GENOTYPE이 P의 GENOTYPE을 포함하는 경우 선택
"""

SELECT 
    C.ID, 
    C.GENOTYPE, 
    P.GENOTYPE AS PARENT_GENOTYPE

FROM ECOLI_DATA AS C
JOIN ECOLI_DATA AS P
ON C.PARENT_ID = P.ID

WHERE (C.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
ORDER BY C.ID;
