'''
1. FISH_INFO와 FISH_NAME_INFO를 FISH_TYPE 기준으로 JOIN
2. FISH_NAME이 BASS, SNAPPER인 행만 SELECT
3. ROW의 개수 COUNT하고 FISH_COUNT로 출력
'''

SELECT COUNT(F.ID) AS FISH_COUNT

FROM FISH_INFO AS F
JOIN FISH_NAME_INFO AS N
ON F.FISH_TYPE = N.FISH_TYPE

WHERE N.FISH_NAME IN ('BASS','SNAPPER')
