"""
1. FIRST_HALF와 ICECREAM_INFO를 FLAVOR 컬럼 기준으로 JOIN
2. 조건: 총 주문량이 3000 보다 큼 / 주 성분이 과일
3. 주문량이 큰 순서대로 결과 정렬
"""

SELECT F.FLAVOR 

FROM FIRST_HALF AS F 
JOIN ICECREAM_INFO AS I 
ON F.FLAVOR = I.FLAVOR 

WHERE F.TOTAL_ORDER >= 3000 AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY F.TOTAL_ORDER DESC;
